### ISSUE TITLE
Downloads for specific game

### ISSUE THREAD

**Issue by scysys** [CBeloch/Xbox-DVR-Downloader#1]
Actually you have this: https://gamerdvr.com/gamer/GAMERTAG/videos
Maybe you can also add: https://gamerdvr.com/games/GAMENAME/videos

**Comment by CBeloch** [comment]
This was meant to download and archive your own content and not that of others.
I'm currently working on a new project and further down the line this project will be updated with new code that uses mostly official APIs and GamerDVR support will be discarded. This was just a fallback anyway
